apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dashboard-proxy
  name: dashboard-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-proxy
  template:
    metadata:
      labels:
        app: dashboard-proxy
    spec:
      containers:
      - args:
        - --cookie-secure=false
        - --provider=github
        - --upstream=http://kubernetes-dashboard.default.svc.cluster.local
        - --http-address=0.0.0.0:8080
        - --redirect-url=https://ops-work.net/oauth2/callback
        - --email-domain=*
        - --github-org=mkarimi20
        - --pass-basic-auth=false
        - --pass-access-token=false
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie
              name: dashboard-proxy-secret
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: dashboard-proxy-secret
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: dashboard-proxy-secret
        image: quay.io/pusher/oauth2_proxy:latest
        name: oauth-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dashboard-proxy
  name: dashboard-proxy
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboard-proxy
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-proxy
  namespace: default
spec:
  rules:
  - host: dashboard.ops-work.net
    http:
      paths:
      - backend:
          serviceName: dashboard-proxy
          servicePort: 80
        path: /
  tls:
  - hosts:
    - dashboard.ops-work.net
    secretName: dashboard-proxy-tls
